export const data = [
    { 'id': 1, title: 'message 1' },
    { 'id': 2, title: 'message 1' },
    { 'id': 3, title: 'message 1' },
    { 'id': 4, title: 'message 1' },
    { 'id': 5, title: 'message 1' },
    { 'id': 6, title: 'message 1' },
    { 'id': 7, title: 'message 1' },
    { 'id': 8, title: 'message 1' },
    { 'id': 9, title: 'message 1' },
    { 'id': 10, title: 'message 1' },
    { 'id': 11, title: 'message 1' },
    { 'id': 12, title: 'message 1' },
    { 'id': 13, title: 'message 1' },
    { 'id': 14, title: 'message 1' },
    { 'id': 15, title: 'message 1' },
    { 'id': 16, title: 'message 1' },
    { 'id': 17, title: 'message 1' },
    { 'id': 18, title: 'message 1' },
    { 'id': 19, title: 'message 1' },
    { 'id': 20, title: 'message 1' },
];
